language: php
php:
  - 8.1
  - 8.2
  - 8.3
before_script:
  - composer require php-coveralls/php-coveralls --no-interaction
script:
  - vendor/bin/phpunit --coverage-clover build/coverage/clover.xml
after_success:
  - php vendor/bin/php-coveralls -v
